version: '2'

services:

  iceworm-dynamodb:
    build: '.'
    image: 'wrmsr/iceworm-dynamodb:latest'
    restart: 'unless-stopped'
    expose:
      - '8000'
    ports:
      - '23120:8000'

  iceworm-minio:
    build: '.'
    image: 'wrmsr/iceworm-minio:latest'
    restart: 'unless-stopped'
    environment:
      MINIO_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE'
      MINIO_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
    expose:
      - '9000'
    ports:
      - '23121:9000'

  iceworm-mongo:
    build: '.'
    image: 'wrmsr/iceworm-mongo:latest'
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'iceworm'
    expose:
      - '27017'
    ports:
      - '23122:27017'

  iceworm-postgres:
    build: '.'
    image: 'wrmsr/iceworm-postgres:latest'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'iceworm'
      POSTGRES_PASSWORD: 'iceworm'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - '5432'
    ports:
      - '23123:5432'

  iceworm-dev:
    build: '.'
    image: 'wrmsr/iceworm-dev:latest'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '..:/iceworm'
    depends_on:
      - 'iceworm-dynamodb'
      - 'iceworm-minio'
      - 'iceworm-mongo'
      - 'iceworm-postgres'
    links:
      - 'iceworm-dynamodb'
      - 'iceworm-minio'
      - 'iceworm-mongo'
      - 'iceworm-postgres'
    expose:
      - '8000'
    ports:
      - '23110:8000'
