version: '2'

services:

  iceworm-postgres-master:
    build: '.'
    image: 'wrmsr/iceworm-postgres:latest'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'iceworm'
      POSTGRES_PASSWORD: 'iceworm'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - '5432'
    ports:
      - '23120:5432'

  iceworm-postgres-slave:
    build: '.'
    image: 'wrmsr/iceworm-postgres:latest'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'iceworm'
      POSTGRES_PASSWORD: 'iceworm'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'iceworm-postgres-master'
    links:
      - 'iceworm-postgres-master'
    depends_on:
      - 'iceworm-postgres-master'
    expose:
      - '5432'
    ports:
      - '23121:5432'

  iceworm-dev:
    build: '.'
    image: 'wrmsr/iceworm-dev:latest'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '..:/iceworm'
    depends_on:
      - 'iceworm-postgres-master'
      - 'iceworm-postgres-slave'
    links:
      - 'iceworm-postgres-master'
      - 'iceworm-postgres-slave'
    expose:
      - '8000'
    ports:
      - '23110:8000'
