"""
TODO:
 - sqla bidir adapter

Types:
 - NUMBER
 - DECIMAL
 - NUMERIC => NUMBER
 - INT, INTEGER, BIGINT, SMALLINT => NUMBER
 - FLOAT, FLOAT4, FLOAT8
 - DOUBLE => FLOAT
 - DOUBLE PRECISION => FLOAT
 - REAL => FLOAT
 - VARCHAR
 - CHAR, CHARACTER => VARCHAR
 - STRING => VARCHAR
 - TEXT => VARCHAR
 - BINARY
 - VARBINARY => BINARY
 - BOOLEAN
 - DATE
 - DATETIME => TIMESTAMP_NTZ
 - TIME
 - TIMESTAMP => TIMESTAMP_NTZ
 - TIMESTAMP_LTZ
 - TIMESTAMP_NTZ
 - TIMESTAMP_TZ
 - VARIANT
 - OBJECT
 - ARRAY
 - GEOGRAPHY
"""
