select 1;
select 'x';
select 1 from x;
select x from y;
select "x" from "y";
select x, y from z;
select f(x, 2) from y;
select x as y from z;
select x and y;
select not z;
select x from y join z;
select x from y join z on 1;
select x from y where 2;
select x from y group by 1;
select null;
select * from x;
select * from (x);
select (1) x;