select 1;
select 'x';
select 1 from x;
select x from y;
select "x" from "y";
select x, y from z;
select f(x, 2) from y;
select x as y from z;
select x and y;
select not z;
select x from y join z;
select x from y join z on 1;
select x from y where 2;
select x from y group by 1;
select null;
select * from x;
select * from (x);
select (1) x;
select 1 - 2;
select -1;
select * from a inner join b;
select * from a left outer join b;
select * from l join r on 1 = 2;
select distinct 1;
select a.b from c.d;
select * from a b;
select * from a as b;
select * from t where a = b;
select distinct m.i as u_i from e.p p left join e.a a on p.a_i = a.i left join e.i i on p.i_i = i.i left join e.i2 ir on i.i_i = ir.i inner join e.u u on c(a.u_i, ir.u_i) = u.i inner join et.u2 m on u.c_u_u = m.u where p.c_a is not null;
select distinct m.i as u_i, t_d(c_t('u', 'a/l_a', c_a)) as dt from e.p p left join e.a a on p.a_i = a.i left join e.i i on p.i_i = i.i left join e.i2 ir on i.i_i = ir.i inner join e.u u on c(a.u_i, ir.u_i) = u.i inner join et.u2 m on u.c_u_u = m.u where p.c_a is not null;
